### ISSUE TITLE
Mi11U MIUI13 安装V1.2版本闪退 及 功能建议

### ISSUE THREAD

**Issue by Jikexiaobai** [FuShengDuoBuYu/AutoBookKeepingBeta#3]
Mi11U MIUI13 安装V1.2版本闪退

功能：
觉得可以增加一个卡包功能 这样更方便知道 各银行卡余额和微信 支付宝 等账户余额

**Comment by FuShengDuoBuYu** [comment]
好的收到
今明两天内将会发布v1.2.5版本(忽然有miui12.5既视感hhh)，专门用于专攻各类异常情况与闪退。

关于功能，建议已收到，会在后面版本更新中仔细考虑的

谢谢你的支持与关注，祝好！

**Comment by Jikexiaobai** [comment]
> 好的收到 今明两天内会发布v1.2.5版(忽然有miui12.5当时感hhh)，专用于各种异常情况与闪退。
> 
> 关于功能，建议已经收到，会在后面版本更新中仔仔细思考的
> 
> 谢谢你的支持与关注，祝好！

辛苦大佬了

**Comment by GT-l** [comment]
realme GT5 Pro直接进入不了软件，刚下下来点进去就闪退
